chore(deps-dev): update to cucumber@1.x
Fails with error:
CompositeParserException: Parser errors:
(28:1): expected: #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty,
got 'Feature: DynamoDB Tables (2012-08-10)'